### ISSUE TITLE
Initialization Error: Unhandled rejection TypeError: this.provider.sendAsync is not a function

### ISSUE THREAD

**Issue by meinto** [ensdomains/ensjs-v2#16]
I applied the fix of the pull request (which is not published to npm yet) https://github.com/Arachnid/ensjs/commit/03c7f5946b2a1064bfef80b7f844bfb966e762da

and initialized the ENS library like follows:

```js
var Web3 = require('web3')
var ENS = require('ethereum-ens')

var provider = new Web3.providers.HttpProvider("https://ropsten.infura.io/TOKEN")
var ens = new ENS(provider)
```

Only this piece of code throws the mentioned error **Unhandled rejection TypeError: this.provider.sendAsync is not a function**. 

The used `HttpProvider` is a testnet (ropsten). Are you familiar with this problem?

used ensjs version is `0.7.3`
used web3 version is `1.0.0-beta.27`

**Comment by Arachnid** [comment]
ensjs doesn't yet support web3 1.0.

**Comment by meinto** [comment]
Ok, thanks for the info. Is there a roadmap supporting web3 version 1.0?

**Comment by Arachnid** [comment]
I've opened an issue for this: https://github.com/Arachnid/ensjs/issues/17

No firm roadmap, but we hope to be able to work on this soon.

**Comment by meinto** [comment]
Ok, thanks! Would be great!
