### ISSUE TITLE
Documentation: function names are given but no examples

### ISSUE THREAD

**Issue by AyushyaChitransh** [ensdomains/ensjs-v2#32]
I am having a tough time to figure out working implementations for the functions mentioned in the readme section. Please can someone add some working examples for them.

**Comment by Arachnid** [comment]
Which functions, and what are you trying to implement?

**Comment by AyushyaChitransh** [comment]
I am trying to reverse resolve ethereum addresses, but I am unable to understand where I am going wrong.

Here is the code I am trying:

```
var ENS = require('ethereum-ens');

var Web3 = require('web3');

var httpProvider= new Web3.providers.HttpProvider('http://localhos:8545');

var ens = new ENS(httpProvider, '0x314159265dd8dbb310642f98f50c066173c1259b');

ens.owner('vitalik.eth').then(function(address){console.log('address is', address)})

ens.owner('d8da6bf26964af9d7eed9e03e53415d37aa96045.addr.reverse').then(function(name){console.log('name is', name)});
```
I am able to get ethereum address but reverse resolution returns 0x0000000000000000000000000000000000000000

**Comment by Arachnid** [comment]
You should be calling `ens.reverse('0xd8da6bf26964af9d7eed9e03e53415d37aa96045').name()`.

**Comment by AyushyaChitransh** [comment]
@Arachnid can you provide an example from mainnet which would resolve to a name? I am getting `ENS name not found` errors for addresses which should return names.

**Comment by Arachnid** [comment]
Try `nickjohnson.eth`.

**Comment by AyushyaChitransh** [comment]
Wow. That works.

So does that mean that other ENS holders have not claimed their name? I am trying to understand why reverse lookup was not working for other addresses.

**Comment by Arachnid** [comment]
Many addresses that have names pointed to them do not have  reverse resolution configured. We're working on getting that more universal.
