### ISSUE TITLE
Permanent registrar

### ISSUE THREAD

**Issue by chrisschaub** [ensdomains/ensjs-v2#39]
Will this code work with registering domains with the new permanent registrar? It seems like I need to use web3 more directly. I am having a tough time finding solid examples of how to register say "foo123.eth" via the new permanent registrar. Any suggestions or sample code is much appreciated.

**Comment by Arachnid** [comment]
ethereum-ens doesn't handle registration, only resolution. For docs on how to do registration, see here: https://docs.ens.domains/contract-api-reference/.eth-permanent-registrar
