### ISSUE TITLE
Empty owner for registered name

### ISSUE THREAD

**Issue by olegabr** [ensdomains/ensjs-v2#40]
The owner function (https://github.com/ensdomains/ensjs/blob/master/index.js#L293) return zero address if "CONTROLLER Not owned yet" is displayed on the corresponding manager's page:  https://manager.ens.domains/name/portofspain.eth

Which method can be used to check that address is registered?

**Comment by Arachnid** [comment]
That's right. `owner` fetches the owner in the ENS registry; .eth is controlled by the registrar contract, and a user can own a name there without having set it up in ENS.

To check if a name is available, call [`available` on the .eth controller contract](https://docs.ens.domains/contract-api-reference/.eth-permanent-registrar/controller#check-name-availability).

**Comment by olegabr** [comment]
Thank you @Arachnid,
Just want to add, that for now the registry contract is here: https://etherscan.io/address/0xf0ad5cad05e10572efceb849f6ff0c68f9700455#readContract

and the `available` function accepts the name without the `.eth` part.
