### ISSUE TITLE
Replace text-encoding with utf8.js and reduce package size by .5 MB

### ISSUE THREAD

**Issue by okwme** [ensdomains/ensjs-v2#43]
We tracked back package bloat to `text-encoding` within `ethereum-ens`. it looks like you're using the package for one line of decoding UTF-8 [here](https://github.com/ensdomains/ensjs/blob/ae6293041661ff4807f42e3057013f223cfbe99d/index.js#L41). Plus `text-encoding` is no longer maintained.

Why not replace the package with https://github.com/mathiasbynens/utf8.js ?

![big-ens](https://user-images.githubusercontent.com/964052/63288039-054bba80-c2bc-11e9-83c6-d81eca63e4c4.png)

**Comment by okwme** [comment]
thanks for merging!
please let us know when you've updated the npm package!

**Comment by Arachnid** [comment]
Published as 0.7.8.
