### ISSUE TITLE
ENS.js package size is too heavy?

### ISSUE THREAD

**Issue by bonustrack** [ensdomains/ensjs-v2#59]
I've integrated ENS.js on a frontend, i've noticed that it take a size of 1.28mb (363kb gzipped) in my app bundle which is relatively heavy. The issue seem that Ethers.js is loaded twice on the pkg, once from `@0xproject/utils` and another with `ethers.js` directly. Anyone have the same issue? You can see the details of the pkgs size within our app here: https://snapshot.org/modern-report.html

**Comment by Arachnid** [comment]
@makoto Would you mind taking a look?

**Comment by bonustrack** [comment]
Thanks it's much lighter now!
