### ISSUE TITLE
Cannot find module 'web3'

### ISSUE THREAD

**Issue by aihunter666** [ensdomains/ensjs-v2#8]
1. npm install ethereum-ens
2. edit test.js:
```
var ENS = require('ethereum-ens');
var Web3 = require('web3');

var web3 = new Web3();
var ens = new ENS(web3);

var address = ens.resolver('onestory.eth').addr().then(function(addr) {
    console.log(addr);
});
```
3. node test.js 
then throw an error: Cannot find module 'web3' 
Where did I get it wrong? thanks

**Comment by Arachnid** [comment]
You need to install `web3` before you can use it.

**Comment by aihunter666** [comment]
@Arachnid thank you very much.   Here's another error after I install ```web3```:
```
Cannot find module 'ethereum-ens'
```

I execute the following command: ```npm install ethereum-ens```, then I runed ```node test.js```, it's throw an error:
```
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "ethereum-ens" under a package
npm ERR! also called "ethereum-ens". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>
```
I don't know what's wrong, please help me. thanks.

btw: 
   node : V8.8.1
   npm: V5.4.2

**Comment by Arachnid** [comment]
To run tests, do `npm test`.
